apiVersion: v1
kind: ServiceAccount
metadata:
  name: network-node-labeller
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: network-node-labeller
rules:
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["get", "list", "patch", "update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: network-node-labeller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: network-node-labeller
subjects:
- kind: ServiceAccount
  name: network-node-labeller
  namespace: default
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: network-node-labeller
spec:
  selector:
    matchLabels:
      app: network-node-labeller
  template:
    metadata:
      labels:
        app: network-node-labeller
    spec:
      serviceAccountName: network-node-labeller
      containers:
      - name: network-node-labeller
        image: docker.io/rocm/k8s-network-node-labeller:v1.0.0
        imagePullPolicy: Always
        securityContext:
          privileged: true
        volumeMounts:
        - name: dev-volume
          mountPath: /dev
        - name: sys-volume
          mountPath: /sys
        - name: nicctl
          mountPath: /usr/sbin/nicctl
        - name: lib-modules
          mountPath: /lib/modules
        - name: opt-amd
          mountPath: /opt/amd
        env:
        - name: DS_NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
      volumes:
      - name: dev-volume
        hostPath:
          path: /dev
          type: Directory
      - name: sys-volume
        hostPath:
          path: /sys
          type: Directory
      - name: nicctl
        hostPath:
          path: /usr/sbin/nicctl
          type: File
      - name: lib-modules
        hostPath:
          path: /lib/modules
          type: Directory
      - name: opt-amd
        hostPath:
          path: /opt/amd
          type: Directory
